// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FreeStructureLazyImport = createFileRoute('/free-structure')()
const DndLazyImport = createFileRoute('/dnd')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FreeStructureLazyRoute = FreeStructureLazyImport.update({
  path: '/free-structure',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/free-structure.lazy').then((d) => d.Route),
)

const DndLazyRoute = DndLazyImport.update({
  path: '/dnd',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dnd.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/dnd': {
      preLoaderRoute: typeof DndLazyImport
      parentRoute: typeof rootRoute
    }
    '/free-structure': {
      preLoaderRoute: typeof FreeStructureLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  DndLazyRoute,
  FreeStructureLazyRoute,
])
